import { Bar, BarChart, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import type { AnalysisResult } from '../../domain/types'
import { formatCurrency } from '../transactions/transactionFormatters'

export function AnalysisCharts({ transactions }: { transactions: AnalysisResult[] }) {
  const genuine = transactions.filter((transaction) => transaction.response?.is_fraud === 0).length
  const fraud = transactions.filter((transaction) => transaction.response?.is_fraud === 1).length
  const categoryMap = new Map<string, { genuine: number; fraud: number }>()
  transactions.forEach((transaction) => { const value = categoryMap.get(transaction.merchant_category) || { genuine: 0, fraud: 0 }; value[transaction.response?.is_fraud === 1 ? 'fraud' : 'genuine'] += transaction.amount; categoryMap.set(transaction.merchant_category, value) })
  const categoryData = Array.from(categoryMap, ([category, value]) => ({ category, ...value })).slice(0, 6)
  const timelineData = [...transactions].reverse().map((transaction) => ({ date: transaction.timestamp.slice(5, 10), amount: transaction.amount, risk: transaction.response?.is_fraud === 1 ? transaction.amount : 0 }))
  const donutData = [{ name: 'No review signal', value: genuine, color: '#2d8a68' }, { name: 'Potential fraud', value: fraud, color: '#d47745' }]
  return <div className="analysis-charts"><article className="panel chart-panel"><div className="panel__heading"><div><p className="eyebrow">Risk overview</p><h2>Review outcomes</h2></div><span className="panel-note">Review outcomes</span></div>{transactions.length ? <div className="analysis-donut"><ResponsiveContainer width="100%" height={230}><PieChart><Pie data={donutData} dataKey="value" nameKey="name" innerRadius={65} outerRadius={90} paddingAngle={3} strokeWidth={0}>{donutData.map((entry) => <Cell key={entry.name} fill={entry.color} />)}</Pie><Tooltip formatter={(value) => Number(value).toLocaleString('en-IN')} /></PieChart></ResponsiveContainer><div className="chart-legend">{donutData.map((entry) => <div key={entry.name}><span className="legend-dot" style={{ background: entry.color }} />{entry.name}<strong>{entry.value}</strong></div>)}</div></div> : <p className="chart-empty">No analyzed transactions yet.</p>}</article><article className="panel chart-panel"><div className="panel__heading"><div><p className="eyebrow">Spending pattern</p><h2>Amount timeline</h2></div><span className="panel-note">INR · by statement date</span></div><ResponsiveContainer width="100%" height={245}><BarChart data={timelineData}><XAxis dataKey="date" tick={{ fontSize: 10 }} axisLine={false} tickLine={false} /><YAxis hide /><Tooltip formatter={(value) => formatCurrency(Number(value))} /><Bar dataKey="amount" name="Spend" radius={[4, 4, 0, 0]} fill="#2d7ea4" /><Bar dataKey="risk" name="Potential fraud" radius={[4, 4, 0, 0]} fill="#d47745" /></BarChart></ResponsiveContainer></article><article className="panel chart-panel chart-panel--wide"><div className="panel__heading"><div><p className="eyebrow">Where signals cluster</p><h2>Spend by category</h2></div><span className="panel-note">By review status</span></div><ResponsiveContainer width="100%" height={245}><BarChart data={categoryData} layout="vertical" margin={{ left: 20, right: 25 }}><XAxis type="number" hide /><YAxis type="category" dataKey="category" width={105} tick={{ fontSize: 10 }} axisLine={false} tickLine={false} /><Tooltip formatter={(value) => formatCurrency(Number(value))} /><Legend /><Bar dataKey="genuine" name="No review signal" stackId="spend" fill="#65aa8a" radius={[0, 0, 0, 0]} /><Bar dataKey="fraud" name="Potential fraud" stackId="spend" fill="#d47745" radius={[0, 4, 4, 0]} /></BarChart></ResponsiveContainer></article></div>
}
