import { ArrowLeft, Download, FileText, ShieldAlert } from 'lucide-react'
import { Link, useSearchParams } from 'react-router-dom'
import { AnalysisCharts } from '../components/analysis/AnalysisCharts'
import { FraudSignalsList } from '../components/analysis/FraudSignalsList'
import { RiskSummary } from '../components/analysis/RiskSummary'
import { PageHeader } from '../components/ui/PageHeader'
import { StateMessage } from '../components/ui/StateMessage'
import { getStatementAnalysis } from '../services/statementHistory'
import { formatCurrency } from '../components/transactions/transactionFormatters'

export function AnalysisResultsPage() {
  const [params] = useSearchParams()
  const analysis = params.get('analysis') ? getStatementAnalysis(params.get('analysis') || '') : undefined
  if (!analysis) return <div className="page-container page-container--narrow"><PageHeader eyebrow="Fraud results" title="No analysis selected" description="Choose a completed statement analysis from the dashboard to review its results." /><section className="panel"><StateMessage type="empty" title="Your results are not available here" description="The analysis may have expired from this browser, or this route was opened directly." action={<Link className="button button--primary" to="/analyze-statement">Upload a statement</Link>} /></section></div>

  const riskLabel = analysis.summary.potentialFraud === 0 ? 'Low review signal' : analysis.summary.potentialFraud <= 2 ? 'Medium review signal' : 'Elevated review required'
  return <div className="page-container"><PageHeader eyebrow="Step 04 · Fraud results" title="Statement analysis complete" description="Your statement has been analyzed. Review the transactions highlighted as potentially requiring attention." action={<div className="results-actions"><Link className="button button--secondary" to="/analyze-statement"><ArrowLeft size={15} />Analyze another</Link><button className="button button--primary" onClick={() => window.print()}><Download size={15} />Save review</button></div>} /><div className="analysis-file-banner"><span className="analysis-file-banner__icon"><FileText size={19} /></span><div><strong>{analysis.statement_name}</strong><span>Completed {new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(analysis.uploaded_at))}</span></div><span className="risk-pill"><ShieldAlert size={15} />{riskLabel}</span></div><RiskSummary summary={analysis.summary} /><section className="risk-callout"><div className="risk-callout__icon"><ShieldAlert size={22} /></div><div><p className="eyebrow">Overall transaction risk</p><h2>{riskLabel}</h2><p>{analysis.summary.potentialFraud ? `${analysis.summary.potentialFraud} of ${analysis.summary.analyzed} transactions may require your attention.` : 'No transactions were highlighted for review.'} Review the transaction details to decide what needs follow-up.</p></div><div className="risk-callout__amount"><span>Potential fraud amount</span><strong>{formatCurrency(analysis.summary.fraudAmount)}</strong></div></section><AnalysisCharts transactions={analysis.transactions} /><FraudSignalsList transactions={analysis.transactions} /><section className="panel suspicious-review-cta"><div><p className="eyebrow">Next step</p><h2>Review suspicious transactions</h2><p>Open the transactions requiring review and inspect each risk signal in context.</p></div><Link className="button button--primary" to="/transactions?prediction=potential_fraud">Review suspicious transactions <ArrowLeft size={15} /></Link></section><section className="panel results-footnote"><ShieldAlert size={17} /><p><strong>Responsible use note:</strong> A highlighted transaction is not confirmation of fraud. If you do not recognize a transaction, contact your card issuer using the number on your card.</p></section></div>
}
