import { ArrowDown, CheckCircle2, ClipboardCheck, FileUp, Gauge, ScanSearch, ShieldCheck } from 'lucide-react'
import { PageHeader } from '../components/ui/PageHeader'

const journey = [
  { icon: FileUp, title: 'Upload Statement', text: 'Choose a credit-card statement PDF. The standalone demo reads the document locally and does not require card numbers, CVV, PINs, or passwords.' },
  { icon: ScanSearch, title: 'Extract Transactions', text: 'Document processing identifies transaction rows where possible and provides clearly labeled sample data when a PDF format cannot be read confidently.' },
  { icon: ClipboardCheck, title: 'Normalize Transaction Data', text: 'Extracted rows are shaped into a consistent transaction representation so they can be searched, reviewed, and analyzed together.' },
  { icon: Gauge, title: 'Analyze Transactions', text: 'The demo analysis service evaluates selected rows and produces deterministic model-based risk signals for the review experience.' },
  { icon: ShieldCheck, title: 'Generate Risk Signals', text: 'Transaction risk analysis groups results into genuine activity and potential fraud signals using a conceptual review threshold.' },
  { icon: CheckCircle2, title: 'Review Transactions', text: 'Review suspicious transactions, inspect probability and context, and decide which activity requires further attention.' },
]

const architecture = ['PDF Statement', 'Document Processing', 'Transaction Extraction', 'Data Normalization', 'Feature Engineering', 'Fraud Detection Model', 'Risk Assessment', 'User Review']

export function HowItWorksPage() {
  return <div className="page-container page-container--narrow"><PageHeader eyebrow="Insights / workflow" title="How Sentinel works" description="A presentation-friendly view of the new statement-upload workflow and the conceptual architecture planned for the final system." /><section className="panel journey-panel"><div className="panel__heading"><div><p className="eyebrow">The Sentinel journey</p><h2>From statement to transactions requiring review</h2></div><span className="panel-note">Standalone demo flow</span></div><section className="workflow-steps">{journey.map((step, index) => <div className="workflow-step" key={step.title}><div className="workflow-step__marker"><step.icon size={19} /></div><div className="workflow-step__body"><span>Step {String(index + 1).padStart(2, '0')}</span><h2>{step.title}</h2><p>{step.text}</p></div>{index < journey.length - 1 && <ArrowDown className="workflow-step__arrow" size={18} aria-hidden="true" />}</div>)}</section></section><section className="panel flow-summary"><p className="eyebrow">Conceptual architecture</p><h2>From document processing to user review</h2><div className="flow-summary__items">{architecture.map((step, index) => <span key={step}>{index + 1}. {step}</span>)}</div><p className="panel-footnote">This is the planned final-system architecture. The current frontend review demonstrates the workflow with browser-local extraction fallback and modular demo analysis; it does not claim that every stage is connected to a running production model.</p></section><section className="panel guide-note"><p className="eyebrow">Responsible use</p><h2>Potential fraud is a model-based risk signal</h2><p>Machine learning can identify patterns that deserve attention, but it does not establish intent or confirm a crime. Sentinel highlights transactions requiring review so a person can investigate them with the appropriate context.</p></section><section className="panel explainer-panel"><p className="eyebrow">Designed for the next phase</p><h2>Modular by design</h2><div className="explanation-list"><Explanation number="01" title="Browser demonstration" text="The review flow uses local sample transactions, analysis results, charts, and statement history so it works without a service connection." /><Explanation number="02" title="Replaceable analysis boundary" text="Demo analysis is isolated in a frontend service that can later be replaced with an approved production integration." /><Explanation number="03" title="Human review" text="Results are presented as potential fraud signals and never as automatic decisions." /><Explanation number="04" title="Future-ready architecture" text="Document processing, normalization, feature engineering, risk assessment, and user review remain explicit stages in the planned system." /></div></section></div>
}

function Explanation({ number, title, text }: { number: string; title: string; text: string }) { return <div className="explanation"><span>{number}</span><div><strong>{title}</strong><p>{text}</p></div></div> }
