import { ArrowDown, CheckCircle2, ClipboardCheck, FileUp, Gauge, ScanSearch, ShieldCheck, UserRound } from 'lucide-react'
import { PageHeader } from '../components/ui/PageHeader'

const journey = [
  { icon: UserRound, title: 'Sign in to the workspace', text: 'Use the clearly labeled local demo account to access Sentinel’s frontend review experience.' },
  { icon: FileUp, title: 'Upload a statement', text: 'Choose a PDF statement. The browser attempts lightweight text extraction and never requires card numbers, CVV, PINs, or passwords.' },
  { icon: ScanSearch, title: 'Extract transactions', text: 'Rows are normalized into a consistent review shape. Unsupported or scanned formats receive a transparent demo fallback.' },
  { icon: ClipboardCheck, title: 'Review extracted data', text: 'Search, filter, select, and inspect statement rows before any model analysis begins.' },
  { icon: ShieldCheck, title: 'Analyze transactions', text: 'Sentinel calls the existing single-transaction prediction contract sequentially, or uses labeled mock predictions when the backend is offline.' },
  { icon: Gauge, title: 'Generate fraud signals', text: 'Results are grouped into genuine and potential-fraud review signals using the model’s returned threshold.' },
  { icon: CheckCircle2, title: 'Review suspicious activity', text: 'Open transaction details, probability, threshold, and model context before deciding what needs attention.' },
]

export function HowItWorksPage() {
  return <div className="page-container page-container--narrow"><PageHeader eyebrow="Insights / workflow" title="How Sentinel works" description="A presentation-friendly view of the statement review journey and the actual machine learning path behind each signal." /><section className="panel journey-panel"><div className="panel__heading"><div><p className="eyebrow">The Sentinel journey</p><h2>From statement to review queue</h2></div><span className="panel-note">Frontend demonstration flow</span></div><section className="workflow-steps">{journey.map((step, index) => <div className="workflow-step" key={step.title}><div className="workflow-step__marker"><step.icon size={19} /></div><div className="workflow-step__body"><span>Step {String(index + 1).padStart(2, '0')}</span><h2>{step.title}</h2><p>{step.text}</p></div>{index < journey.length - 1 && <ArrowDown className="workflow-step__arrow" size={18} aria-hidden="true" />}</div>)}</section></section><section className="panel flow-summary"><p className="eyebrow">Actual ML flow</p><h2>Frontend → FastAPI → Random Forest → result</h2><div className="flow-summary__items"><span>1. Validate eight fields</span><span>2. POST /predict</span><span>3. Backend preprocessing</span><span>4. Random Forest probability</span><span>5. 65% threshold</span><span>6. Result + local history</span></div><p className="panel-footnote">The statement workflow is frontend orchestration. The backend remains responsible for preprocessing and the saved model; no additional engineered fields are sent from the browser.</p></section><section className="panel guide-note"><p className="eyebrow">Responsible use</p><h2>Potential Fraud is a probabilistic review signal</h2><p>Machine learning performs classification from patterns in the selected dataset; it does not establish intent or confirm a crime. This is an academic prototype. Real banking systems require much larger and continuously updated datasets, strong security, monitoring, human review, and regulatory controls. Sentinel’s local history is a browser convenience, not a bank transaction database.</p></section><section className="panel explainer-panel"><p className="eyebrow">What stays unchanged</p><h2>Existing backend contract</h2><div className="explanation-list"><Explanation number="01" title="GET /health" text="The sidebar continues to show whether FastAPI and the saved model are available." /><Explanation number="02" title="POST /predict" text="Statement analysis requests keep the original eight transaction fields." /><Explanation number="03" title="Model metadata" text="The real Random Forest dataset metrics and threshold remain available in Model Insights." /><Explanation number="04" title="Demo fallback" text="Offline statement reviews use synthetic frontend predictions and say so clearly in the results." /></div></section></div>
}

function Explanation({ number, title, text }: { number: string; title: string; text: string }) { return <div className="explanation"><span>{number}</span><div><strong>{title}</strong><p>{text}</p></div></div> }
