import { useEffect, useState } from 'react'
import { ArrowLeft, CalendarDays, MapPin, ShieldAlert, Store } from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import type { StoredTransaction } from '../domain/types'
import { getPrediction, subscribeToHistory } from '../services/transactionHistory'
import { PageHeader } from '../components/ui/PageHeader'
import { StateMessage } from '../components/ui/StateMessage'
import { StatusBadge } from '../components/ui/StatusBadge'
import { formatCurrency, formatDate, formatProbability, formatTime } from '../components/transactions/transactionFormatters'

export function TransactionDetailsPage() {
  const { transactionId } = useParams()
  const [transaction, setTransaction] = useState<StoredTransaction>()
  const [loading, setLoading] = useState(true)
  useEffect(() => { if (!transactionId) { setLoading(false); return } setTransaction(getPrediction(transactionId)); setLoading(false); return subscribeToHistory(() => setTransaction(getPrediction(transactionId))) }, [transactionId])
  return <div className="page-container page-container--narrow"><PageHeader eyebrow="Transactions / details" title="Transaction details" description="Review the transaction information and its review status." action={<Link className="button button--secondary" to="/transactions"><ArrowLeft size={16} />Back to transactions</Link>} />{loading && <StateMessage type="loading" title="Loading transaction" description="Please wait while the transaction details load." />}{!loading && !transaction && <StateMessage type="error" title="Transaction unavailable" description="This transaction is no longer available. Upload and analyze a statement to review its transactions." action={<Link className="button button--secondary" to="/dashboard">Return to dashboard</Link>} />}{transaction && <><section className={`detail-hero ${transaction.is_fraud === 1 ? 'detail-hero--warning' : 'detail-hero--positive'}`}><div><p className="eyebrow">Transaction review</p><h2>{transaction.is_fraud === 1 ? 'Requires review' : 'No potential fraud detected'}</h2><p>{transaction.is_fraud === 1 ? 'This transaction may require your attention.' : 'No potential fraud signal was identified for this transaction.'}</p></div><StatusBadge prediction={transaction.is_fraud === 1 ? 'potential_fraud' : 'genuine'} /></section><section className="detail-grid"><article className="panel"><div className="panel__heading"><div><p className="eyebrow">Transaction summary</p><h2>Transaction information</h2></div></div><div className="detail-list"><DetailRow icon={Store} label="Merchant" value={transaction.merchant_name || 'Merchant details unavailable'} /><DetailRow icon={CalendarDays} label="Date" value={`${formatDate(transaction.timestamp)} at ${formatTime(transaction.timestamp)}`} /><DetailRow icon={MapPin} label="Category" value={transaction.merchant_category} /><DetailRow icon={MapPin} label="Location" value={transaction.location} /><DetailRow icon={ShieldAlert} label="Status" value={transaction.is_fraud === 1 ? 'Requires review' : 'Reviewed'} /></div></article><article className="panel"><div className="panel__heading"><div><p className="eyebrow">Review signal</p><h2>Potential fraud</h2></div><ShieldAlert size={19} className={transaction.is_fraud === 1 ? 'warning-icon' : 'success-icon'} /></div><div className="metric-list"><div><span>Amount</span><strong>{formatCurrency(transaction.amount)}</strong></div><div><span>Fraud probability</span><strong>{formatProbability(transaction.fraud_probability)}</strong></div></div><p className="result-note"><ShieldAlert size={14} />{transaction.is_fraud === 1 ? 'This transaction was highlighted for review. Check that the merchant, amount, date, and location are familiar.' : 'No review signal was raised for this transaction.'}</p></article></section></>}</div>
}

function DetailRow({ icon: Icon, label, value }: { icon: LucideIcon; label: string; value: string }) { return <div className="detail-row"><span className="detail-row__icon"><Icon size={16} /></span><span>{label}</span><strong>{value}</strong></div> }
