import { useEffect, useState } from 'react'
import { ArrowLeft, CalendarDays, Cpu, Globe2, MapPin, UserRound } from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import type { StoredTransaction } from '../domain/types'
import { getPrediction, subscribeToHistory } from '../services/transactionHistory'
import { PageHeader } from '../components/ui/PageHeader'
import { StateMessage } from '../components/ui/StateMessage'
import { StatusBadge } from '../components/ui/StatusBadge'
import { formatCurrency, formatDate, formatProbability, formatTime } from '../components/transactions/transactionFormatters'

export function TransactionDetailsPage() {
  const { transactionId } = useParams()
  const [transaction, setTransaction] = useState<StoredTransaction>()
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    if (!transactionId) {
      setLoading(false)
      return
    }
    setTransaction(getPrediction(transactionId))
    setLoading(false)
    return subscribeToHistory(() => setTransaction(getPrediction(transactionId)))
  }, [transactionId])

  return <div className="page-container page-container--narrow">
    <PageHeader eyebrow="Prediction record" title="Transaction details" description="Review the original transaction fields and the real model output saved in this browser." action={<Link className="button button--secondary" to="/transactions"><ArrowLeft size={16} />Back to history</Link>} />
    {loading && <StateMessage type="loading" title="Loading prediction" description="Fetching the saved local record." />}
    {!loading && !transaction && <StateMessage type="error" title="Prediction unavailable" description="This application prediction ID is not stored in the current browser." action={<Link className="button button--secondary" to="/transactions">Return to history</Link>} />}
    {transaction && <>
      <section className={`detail-hero ${transaction.is_fraud === 1 ? 'detail-hero--warning' : 'detail-hero--positive'}`}><div><p className="eyebrow">Model prediction</p><h2>{transaction.is_fraud === 1 ? 'Potential Fraud' : 'Genuine'}</h2><p>{formatProbability(transaction.fraud_probability)} fraud probability returned by the model.</p></div><StatusBadge prediction={transaction.is_fraud === 1 ? 'potential_fraud' : 'genuine'} /></section>
      <section className="detail-grid"><article className="panel"><div className="panel__heading"><div><p className="eyebrow">Transaction information</p><h2>Payment context</h2></div></div><div className="detail-list"><DetailRow icon={CalendarDays} label="Transaction time" value={`${formatDate(transaction.timestamp)} at ${formatTime(transaction.timestamp)}`} /><DetailRow icon={Globe2} label="Location" value={`${transaction.location} · ${transaction.is_foreign_transaction ? 'Foreign' : 'Domestic'}`} /><DetailRow icon={Cpu} label="Device type" value={transaction.device_type} /><DetailRow icon={MapPin} label="Merchant category" value={transaction.merchant_category} /><DetailRow icon={UserRound} label="User age" value={`${transaction.user_age} years`} /></div></article><article className="panel"><div className="panel__heading"><div><p className="eyebrow">Amount and account</p><h2>Input details</h2></div></div><div className="metric-list"><div><span>Amount</span><strong>{formatCurrency(transaction.amount)}</strong></div><div><span>Account age</span><strong>{transaction.account_age_days.toLocaleString()} days</strong></div><div><span>Fraud probability</span><strong>{formatProbability(transaction.fraud_probability)}</strong></div><div><span>Decision threshold</span><strong>{formatProbability(transaction.threshold)}</strong></div></div></article></section>
      <section className="panel"><div className="panel__heading"><div><p className="eyebrow">Prediction metadata</p><h2>Result details</h2></div></div><div className="detail-metadata"><div><span>Application prediction ID</span><strong>{transaction.transaction_id}</strong><small>Generated by Sentinel for browser-local history; not a bank transaction ID.</small></div><div><span>Checked at</span><strong>{formatDate(transaction.checked_at)} at {formatTime(transaction.checked_at)}</strong></div><div><span>Returned fraud flag</span><strong>{transaction.is_fraud === 1 ? '1 — potential fraud signal' : '0 — genuine signal'}</strong></div></div></section>
    </>}
  </div>
}

function DetailRow({ icon: Icon, label, value }: { icon: LucideIcon; label: string; value: string }) {
  return <div className="detail-row"><span className="detail-row__icon"><Icon size={16} /></span><span>{label}</span><strong>{value}</strong></div>
}
